build: off

environment:
  PYTHON_VERSION: 3.6
  MINICONDA: C:\\Miniconda36-x64

  matrix:
    - TEST_FILES: "tests\ --ignore=tests\test_qdf.py --ignore=tests\test_pv2qdf.py --ignore=tests\test_diskdf.py --ignore=tests\test_orbit.py --ignore=tests\test_streamdf.py --ignore=tests\test_streamgapdf.py --ignore=tests\test_evolveddiskdf.py --ignore=tests\test_quantity.py --ignore=tests\test_nemo.py --ignore=tests\test_coords.py"
      REQUIRES_ASTROPY: $False

    - TEST_FILES: tests\test_orbit.py
      REQUIRES_ASTROPY: $True

    - TEST_FILES: tests\test_quantity.py tests\test_coords.py
      REQUIRES_ASTROPY: $True

platform:
    - x64

install:
  - cmd: call %MINICONDA%\Scripts\activate.bat
  - cmd: conda.exe update --yes --quiet conda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy matplotlib setuptools pip cython>=0.20 pytest gsl"
  - activate test-environment
  - pip install coverage
  - pip install pytest-cov
  - If ( %$REQUIRES_ASTROPY% ) {conda install astropy}

  # Environment variables for GSL linking
  - set INCLUDE=%CONDA_PREFIX%\Library\include;%INCLUDE%
  - set LIB=%CONDA_PREFIX%\Library\lib;%LIB%
  - set LIBPATH=%CONDA_PREFIX%\Library\lib;%LIBPATH%

  - python setup.py build_ext --single_ext --inplace --no-openmp
  - python setup.py develop --single_ext

test_script:
  - pytest -v %TEST_FILES% --cov galpy --cov-config .coveragerc_travis --disable-pytest-warnings
