name: Build Mac OS X & Windows wheels

# Update on every push
on:
  push:
    branches:    
      - master
      - macwheels
    paths-ignore:
      - 'doc/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
  release:
    types: [created]

jobs:
  build:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest,windows-latest]
        python-version: [3.5,3.6,3.7, 3.8]
    steps:
      # check-out this repository
      - uses: actions/checkout@v2
      # Install Miniconda, as specificed by this repository's environment.yml
      - uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: galpywheels
           environment-file: .github/conda-build-environment-${{ matrix.os }}.yml
           python-version: ${{ matrix.python-version }}
      - name: Install pip dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install wheel
      - name: Set environment variables on Mac OS
        if: matrix.os == 'macos-latest'
        shell: bash -l {0}
        run: |
          echo ::set-env name=CFLAGS::-I$CONDA_PREFIX/include
          echo ::set-env name=LDFLAGS::-I$CONDA_PREFIX/lib
          echo ::set-env name=LD_LIBRARY_PATH::-I$CONDA_PREFIX/lib
      - name: Set environment variables on Windows
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: |
          echo ::set-env name=INCLUDE::$CONDA_PREFIX\Library\include
          echo ::set-env name=LIB::$CONDA_PREFIX\Library\lib
          echo ::set-env name=LIBPATH::$CONDA_PREFIX\Library\lib
      - name: Build extension
        shell: bash -l {0}
        run: |
          mkdir wheelhouse
          python setup.py build_ext
      - name: Build wheel
        shell: bash -l {0}
        run: python setup.py bdist_wheel -d wheelhouse
      # Upload wheel as artifact
      - uses: actions/upload-artifact@v2-preview
        with:
          name: galpy-wheel-python-${{ matrix.python-version }}-${{ matrix.os }}
          path: wheelhouse/*.whl
  combine:
    name: Combine wheels into single artifact
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir tmp_wheelhouse
          mkdir wheelhouse
      - uses: actions/download-artifact@v2-preview
        with:
          path: tmp_wheelhouse/
      - run: find tmp_wheelhouse/ -mindepth 2 -type f -exec mv -i '{}' wheelhouse/ ';'
      - uses: actions/upload-artifact@v2-preview
        with:
          name: galpy-wheels-macos-windows-latest
          path: wheelhouse/*.whl
